person_list/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create/$', views.create, name='create'),
	url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<person_id>[0-9]+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<person_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

person_list_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^person_list/', include('person_list.urls', namespace="person_list")),
    url(r'^admin/', include(admin.site.urls)),
]

person_list/models.py
from datetime import date

from django.db import models


class Person(models.Model):
	first_name = models.CharField(max_length=40)
	last_name = models.CharField(max_length=40)
	date_of_birth = models.DateField()
	zip_code = models.CharField(max_length=10)

	def __unicode__(self):
		return '{} {} was born on {} and lives in {}'.format(self.first_name, self.last_name, self.date_of_birth, self.zip_code)

	def was_born_in_past(self):
		return self.date_of_birth <= date.today()

person_list/forms.py
from django.forms import ModelForm

from .models import Person

class PersonForm(ModelForm):
	class Meta:
		model = Person
		fields = ['last_name', 'first_name', 'date_of_birth', 'zip_code']

person_list/views.py
from datetime import date

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import PersonForm
from .models import Person

def index(request):
	person_list = Person.objects.filter(
		date_of_birth__lte=date.today()
	)
	return render(request, 'person_list/index.html', {'person_list': person_list})

def create(request):
	if request.method == 'POST':
		form_submission = PersonForm(request.POST)
		if form_submission.is_valid():
			new_person = form_submission.save()
			return HttpResponseRedirect(reverse('person_list:detail', args=[new_person.id]))
	person_form = PersonForm()
	return render(request, 'person_list/create.html', {'person_form': person_form})

def detail(request, person_id):
	try:
		person = Person.objects.get(pk=person_id)
	except Person.DoesNotExist:
		return redirect_to_index()
	else:
		return render(request, 'person_list/detail.html', {'person': person})

def edit(request, person_id):
	try:
		person = Person.objects.get(pk=person_id)
	except Person.DoesNotExist:
		return redirect_to_index()
	else:
		if request.method == 'POST':
			form_submission = PersonForm(data=request.POST or None, instance=person)
			if form_submission.is_valid():
				form_submission.save()
				return HttpResponseRedirect(reverse('person_list:detail', args=[person_id]))
		person_form = PersonForm(instance=person)
		return render(request, 'person_list/edit.html', {'person_form': person_form, 'person': person})

def delete(request, person_id):
	try:
		person = Person.objects.get(pk=person_id)
	except Person.DoesNotExist:
		return redirect_to_index()
	else:
		if request.method == 'POST':
			person.delete()
			return redirect_to_index()
		return render(request, 'person_list/delete.html', {'person': person})

def redirect_to_index():
	return HttpResponseRedirect(reverse('person_list:index'))

person_list/templates/person_list/base_layout.html
<!DOCTYPE html>
<html>
<head>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

{% block head_scripts %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'person_list:index' %}">Person List</a>
    </div>
  </div>
</nav>

<div class="container">
{% block body %}{% endblock body %}
</div>
{% block body_scripts %}{% endblock %}
</body>
</html>

person_list/templates/person_list/create.html
{% extends "person_list/base_layout.html" %}

{% block head_scripts %}
	<link rel="stylesheet" href="https://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/css/datepicker3.css"></link>
	<script src="https://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
{% endblock %}

{% block body %}

<a class="btn btn-default" role="button" href="{% url 'person_list:index' %}">&lt; Back to index page</a>

<div class="page-header">
	<h4>Create a New Person</h4>
</div>

{% if person_form %}
	<form action="{% url 'person_list:create' %}" method="post">
		{% csrf_token %}
		{{ person_form.as_p }}
		<button class="btn btn-primary" type="submit">Save</button>
	</form>
{% endif %}

{% endblock body %}

{% block body_scripts %}
<script>
	$('#id_date_of_birth').datepicker({
		format: "yyyy-mm-dd"
	});
</script>
{% endblock %}

person_list/templates/person_list/delete.html
{% extends "person_list/base_layout.html" %}

{% block body %}

<a class="btn btn-default" role="button" href="{% url 'person_list:detail' person.id %}">&lt; Back to detail page</a>

<h2>Delete Person?</h2>

<p>Are you sure you want to delete <strong>{{ person.last_name }}, {{ person.first_name}}</strong> from our records?</p>
<form action="{% url 'person_list:delete' person.id %}" method="post">
	{% csrf_token %}
	<button class="btn btn-danger" type="submit">DELETE</button>
</form>

{% endblock body %}

person_list/templates/person_list/detail.html
{% extends "person_list/base_layout.html" %}

{% block body %}

<a class="btn btn-default" role="button" href="{% url 'person_list:index' %}">&lt; Back to index page</a><br/>

<div class="page-header">
	<h4>Person Detail</h4>
</div>
<div class="row">
	<div class="col-sm-4">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">{{ person.last_name }}, {{ person.first_name }}</h3>
			</div>
			<div class="panel-body">
				<span>DoB: {{ person.date_of_birth }}</span><br/>
				<span>Zip: {{ person.zip_code }}</span>
			</div>
		</div>
	</div>
</div>

<p>
	<a class="btn btn-primary btn-large" role="button" href="{% url 'person_list:edit' person.id %}">EDIT</a>
	<a class="btn btn-danger btn-large" role="button" href="{% url 'person_list:delete' person.id %}">DELETE</a>
</p>


{% endblock body %}

person_list/templates/person_list/edit.html
{% extends "person_list/base_layout.html" %}

{% block head_scripts %}
	<link rel="stylesheet" href="https://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/css/datepicker3.css"></link>
	<script src="https://eternicode.github.io/bootstrap-datepicker/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
{% endblock %}

{% block body %}

<a class="btn btn-default" role="button" href="{% url 'person_list:detail' person.id %}">&lt; Back to detail page</a>

<div class="page-header">
	<h4>Editing Person: {{ person.last_name }}, {{ person.first_name }}</h4>
</div>

{% if person_form %}
	<form action="{% url 'person_list:edit' person.id %}" method="post">
		{% csrf_token %}
		{{ person_form.as_p }}
		<button class="btn btn-primary" type="submit">Save</button>
	</form>
{% endif %}

{% endblock body %}

{% block body_scripts %}
<script>
	$('#id_date_of_birth').datepicker({
		format: "yyyy-mm-dd"
	});
</script>
{% endblock %}

person_list/templates/person_list/index.html
{% extends "person_list/base_layout.html" %}

{% block body %}
<div class="row">
{% if person_list %}
	<div class="col-sm-4">
		<ul class="list-group">
		{% for person in person_list %}
			<li class="list-group-item"><a href="{% url 'person_list:detail' person.id %}">{{ person.last_name }}, {{ person.first_name }}</a></li>
		{% endfor %}
		</ul>
	</div>
{% else %}
	<p>No people have been entered into this list.</p>
{% endif %}
</div>

<a class="btn btn-primary btn-large" role="button" href="{% url 'person_list:create' %}">Create New Person</a>

{% endblock body %}